services:
  db:
    image: postgres:18
    container_name: familytree_db
    environment:
      POSTGRES_USER: family
      POSTGRES_PASSWORD: family
      POSTGRES_DB: familytree
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: